version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_development
    ports:
      - "3306:3306"

  node_app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql_db
    environment:
      DB_HOST: mysql_db # Service name as hostname
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: database_development